export const USER_LOGED_IN = "USER_LOGED_IN";
export const UPDATE_FARMING_TIPS = "UPDATE_FARMING_TIPS";
export const UPDATE_ACTIVE_TIPS = "UPDATE_ACTIVE_TIPS";
export const UPDATE_TEMPERATURE = "UPDATE_TEMPERATURE";
export const UPDATE_DATE = "UPDATE_DATE";
export const UPDATE_STREAMING_URI = "UPDATE_STREAMING_URI";